keycloak:
  realm: blog
  auth-server-url: ${SSO_ADDRESS}
  resource: comment-service
  bearer-only: true
  principal-attribute: preferred_username
  credentials:
    secret: ${SSO_SECRET}

spring.data.mongodb:
  port: 27017
  host: comment-database
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  authentication-database: ${DB_NAME}
  database: ${DB_NAME}